// Auto-generated by scripts/generate-runtime-error-maps.mjs. Do not edit manually.

export const CHAT_ERROR_MAP = {
  "common": {},
  "apis": {
    "sendMessage": {
      "range": "110,215,300,500,1200",
      "localErrors": {
        "sendMessage": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          },
          "not_connected": {
            "code": 300,
            "retryable": true
          },
          "encode_failed": {
            "code": 500,
            "retryable": false
          }
        }
      },
      "errors": {
        "MESSAGE_BLOCKED": {
          "code": 1200
        },
        "USER_MUTED": {
          "code": 215
        }
      }
    },
    "getHistoryMessages": {
      "range": "4,110,202,505",
      "localErrors": {
        "getHistoryMessages": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "service_not_enabled": {
          "code": 505
        },
        "page_size_exceeded": {
          "code": 110,
          "aliases": [
            "pull number cannot be greater",
            "limit is to large"
          ]
        }
      }
    },
    "removeHistoryMessages": {
      "range": "110,112,202,505",
      "localErrors": {
        "removeHistoryMessages": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "service_not_enabled": {
          "code": 505
        },
        "query_param_reaches_limit": {
          "code": 112,
          "aliases": [
            "delete msg list limit"
          ]
        }
      }
    },
    "getGroupMessageReadUsers": {
      "range": "4,110,500",
      "localErrors": {
        "getGroupMessageReadUsers": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "message_not_found": {
          "code": 500
        }
      }
    },
    "markConversationRead": {
      "range": "110,201,300,500",
      "localErrors": {
        "markConversationRead": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "not_login": {
          "code": 201
        },
        "not_connected": {
          "code": 300
        },
        "message_invalid": {
          "code": 500
        }
      }
    },
    "markMessageRead": {
      "range": "110,300",
      "localErrors": {
        "markMessageRead": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "invalid_direction": {
          "code": 110
        },
        "not_connected": {
          "code": 300
        }
      }
    },
    "recallMessage": {
      "range": "110,201,300,504,505",
      "localErrors": {
        "recallMessage": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "message_invalid": {
          "code": 110
        },
        "not_login": {
          "code": 201
        },
        "not_connected": {
          "code": 300
        },
        "recall_time_limit": {
          "code": 504
        },
        "recall_disabled": {
          "code": 505
        }
      }
    },
    "updateMessage": {
      "range": "110,111,201,210,300,511",
      "localErrors": {
        "modifyMessage": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          },
          "unsupported_type": {
            "code": 111,
            "retryable": false
          }
        }
      },
      "errors": {
        "message_invalid": {
          "code": 110
        },
        "unsupported_type": {
          "code": 111
        },
        "not_login": {
          "code": 201
        },
        "permission_denied": {
          "code": 210
        },
        "not_connected": {
          "code": 300
        },
        "edit_failed": {
          "code": 511
        }
      }
    },
    "downloadMessageAttachment": {
      "range": "400,401,403,407",
      "localErrors": {
        "downloadAttachment": {
          "validation_invalid": {
            "code": 401,
            "retryable": false
          }
        }
      },
      "errors": {
        "not_found": {
          "code": 400,
          "httpStatus": 404
        },
        "invalid": {
          "code": 401
        },
        "download_failed": {
          "code": 403
        },
        "expired": {
          "code": 407,
          "httpStatus": 404
        }
      }
    },
    "downloadAndParseCombineMessage": {
      "range": "110,401,403,500",
      "localErrors": {
        "downloadAndParseCombineMessage": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "invalid_param": {
          "code": 110
        },
        "invalid_type": {
          "code": 500
        },
        "parse_failed": {
          "code": 401
        },
        "download_failed": {
          "code": 403
        }
      }
    },
    "addReaction": {
      "range": "110,302,505,600,602,1300-1302",
      "localErrors": {
        "addReaction": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "reaction_already_operated": {
          "code": 1301
        },
        "reaction_reach_limit": {
          "code": 1300
        },
        "group_not_joined": {
          "code": 602
        },
        "reaction_operation_illegal": {
          "code": 1302
        },
        "service_not_enabled": {
          "code": 505
        },
        "server_busy": {
          "code": 302
        }
      }
    },
    "removeReaction": {
      "range": "110,505,1301,1302",
      "localErrors": {
        "removeReaction": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "service_not_enabled": {
          "code": 505
        },
        "reaction_operation_illegal": {
          "code": 1302
        }
      }
    },
    "getReactionList": {
      "range": "110,505,600",
      "localErrors": {
        "getReactionList": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "service_not_enabled": {
          "code": 505
        },
        "group_invalid_id": {
          "code": 600
        }
      }
    },
    "getReactionDetail": {
      "range": "110,505,1302",
      "localErrors": {
        "getReactionDetail": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "service_not_enabled": {
          "code": 505
        },
        "reaction_operation_illegal": {
          "code": 1302
        }
      }
    },
    "pinMessage": {
      "range": "4,110",
      "errors": {
        "pin_msg_id_illegal": {
          "code": 110
        },
        "pin_message_limit": {
          "code": 4,
          "aliases": [
            "91101"
          ]
        },
        "pin_message_not_found": {
          "code": 110,
          "aliases": [
            "91102"
          ]
        }
      }
    },
    "unpinMessage": {
      "range": "110",
      "errors": {
        "pin_msg_id_illegal": {
          "code": 110
        },
        "pin_message_not_found": {
          "code": 110,
          "aliases": [
            "91102",
            "user session pin message not exist"
          ]
        }
      }
    },
    "getPinnedMessageList": {
      "range": "110,111",
      "errors": {
        "operation_unsupported": {
          "code": 111,
          "aliases": [
            "15002"
          ]
        },
        "pin_message_not_found": {
          "code": 110,
          "aliases": [
            "91102",
            "user session pin message not exist"
          ]
        }
      }
    },
    "getSupportedTranslationLanguages": {
      "range": "505",
      "errors": {
        "service_not_enabled": {
          "code": 505,
          "aliases": [
            "service not open!"
          ]
        }
      }
    },
    "translateMessage": {
      "range": "505,1110-1113",
      "localErrors": {
        "translateMessage": {
          "validation_invalid": {
            "code": 1110,
            "retryable": false
          }
        }
      },
      "errors": {
        "translate_text_too_long": {
          "code": 1110
        },
        "translate_param_invalid": {
          "code": 1110
        },
        "service_not_enabled": {
          "code": 1111,
          "aliases": [
            "service not open!"
          ]
        },
        "translate_usage_limit": {
          "code": 1112,
          "aliases": [
            "The request has reached the maximum limit"
          ]
        },
        "translate_failed": {
          "code": 1113,
          "aliases": [
            "The request failed, please try again later."
          ]
        }
      }
    },
    "voiceMessageToText": {
      "range": "4,110,202,407-411,505",
      "localErrors": {
        "voiceMessageToText": {
          "validation_invalid": {
            "code": 407,
            "retryable": false
          },
          "file_not_found": {
            "code": 410,
            "retryable": false
          }
        }
      },
      "errors": {
        "unauthorized": {
          "code": 202,
          "retryable": true
        },
        "file_not_found": {
          "code": 410,
          "retryable": false,
          "aliases": [
            "4041001"
          ]
        },
        "file_invalid": {
          "code": 407,
          "retryable": false,
          "aliases": [
            "4001002"
          ]
        },
        "duration_too_long": {
          "code": 408,
          "retryable": false,
          "aliases": [
            "4001003"
          ]
        },
        "file_too_large": {
          "code": 411,
          "retryable": false,
          "aliases": [
            "4001001"
          ]
        },
        "service_not_enabled": {
          "code": 505,
          "retryable": false,
          "aliases": [
            "4031001"
          ]
        },
        "service_limit_exceeded": {
          "code": 4,
          "retryable": true,
          "aliases": [
            "4031002"
          ]
        },
        "voice_to_text_failed": {
          "code": 409,
          "retryable": true,
          "aliases": [
            "5021003",
            "5001003"
          ]
        }
      }
    },
    "voiceFileToText": {
      "range": "4,110,202,402,407-411,505",
      "localErrors": {
        "voiceFileToText": {
          "validation_invalid": {
            "code": 407,
            "retryable": false
          },
          "upload_required": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "unauthorized": {
          "code": 202,
          "retryable": true
        },
        "upload_failed": {
          "code": 402,
          "retryable": true,
          "aliases": [
            "5021001"
          ]
        },
        "file_invalid": {
          "code": 407,
          "retryable": false,
          "aliases": [
            "4001002"
          ]
        },
        "duration_too_long": {
          "code": 408,
          "retryable": false,
          "aliases": [
            "4001003"
          ]
        },
        "file_too_large": {
          "code": 411,
          "retryable": false,
          "aliases": [
            "4001001"
          ]
        },
        "service_not_enabled": {
          "code": 505,
          "retryable": false,
          "aliases": [
            "4031001"
          ]
        },
        "service_limit_exceeded": {
          "code": 4,
          "retryable": true,
          "aliases": [
            "4031002"
          ]
        },
        "voice_to_text_failed": {
          "code": 409,
          "retryable": true,
          "aliases": [
            "5021003",
            "5001003"
          ]
        }
      }
    },
    "getConversationList": {
      "range": "110",
      "localErrors": {
        "getConversationList": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {}
    },
    "getPinnedConversationList": {
      "range": "110",
      "localErrors": {
        "getPinnedConversationList": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {}
    },
    "getConversationListByMark": {
      "range": "110",
      "localErrors": {
        "getConversationListByMark": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {}
    },
    "deleteConversation": {
      "range": "110",
      "localErrors": {
        "deleteConversation": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {}
    },
    "setConversationPinned": {
      "range": "110",
      "localErrors": {
        "setConversationPinned": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {}
    },
    "addConversationMark": {
      "range": "110",
      "localErrors": {
        "addConversationMark": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {}
    },
    "removeConversationMark": {
      "range": "110",
      "localErrors": {
        "removeConversationMark": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {}
    },
    "clearAllMessagesAndConversations": {
      "range": "",
      "errors": {}
    },
    "searchMessages": {
      "range": "110,505",
      "localErrors": {
        "searchMessages": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "service_not_enabled": {
          "code": 505
        }
      }
    }
  }
} as const;
