// Auto-generated by scripts/generate-runtime-error-maps.mjs. Do not edit manually.

export const CHATROOM_ERROR_MAP = {
  "common": {},
  "apis": {
    "getChatRoomList": {
      "range": "",
      "errors": {}
    },
    "getChatRoomInfo": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "updateChatRoomInfo": {
      "range": "110,210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "forbidden_op": {
          "code": 110,
          "httpStatus": 403,
          "retryable": false
        },
        "illegal_argument": {
          "code": 110,
          "httpStatus": 400,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "destroyChatRoom": {
      "range": "210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "joinChatRoom": {
      "range": "4,606,704,707",
      "errors": {
        "exceed_limit": {
          "code": 4,
          "httpStatus": 403,
          "retryable": false
        },
        "members_full": {
          "code": 704,
          "httpStatus": 403,
          "retryable": false,
          "matchField": "error_description",
          "matchPattern": "member list is full"
        },
        "user_in_blocklist": {
          "code": 707,
          "httpStatus": 403,
          "retryable": false,
          "matchField": "error_description",
          "matchPattern": "is in the blacklist"
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "leaveChatRoom": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getChatRoomMemberList": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "addChatRoomMembers": {
      "range": "110,204,210,606",
      "errors": {
        "illegal_argument": {
          "code": 110,
          "httpStatus": 400,
          "retryable": false
        },
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        },
        "service_resource_not_found": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "removeChatRoomMembers": {
      "range": "210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getChatRoomAdminList": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "setChatRoomAdmin": {
      "range": "204,210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        },
        "service_resource_not_found": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "removeChatRoomAdmin": {
      "range": "210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getChatRoomMuteList": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "muteChatRoomMembers": {
      "range": "110,210,606",
      "errors": {
        "illegal_argument": {
          "code": 110,
          "httpStatus": 400,
          "retryable": false
        },
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "unmuteChatRoomMembers": {
      "range": "210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "muteAllChatRoomMembers": {
      "range": "210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "unmuteAllChatRoomMembers": {
      "range": "210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "isCurrentUserMutedInChatRoom": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getChatRoomBlocklist": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "blockChatRoomMembers": {
      "range": "204,210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        },
        "service_resource_not_found": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "unblockChatRoomMembers": {
      "range": "210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getChatRoomAllowlist": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "addUsersToChatRoomAllowlist": {
      "range": "204,210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        },
        "service_resource_not_found": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "removeUsersFromChatRoomAllowlist": {
      "range": "210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "checkIfInChatRoomAllowList": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getChatRoomAnnouncement": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "updateChatRoomAnnouncement": {
      "range": "110,210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "forbidden_op": {
          "code": 110,
          "httpStatus": 403,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getChatRoomSharedFileList": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "deleteChatRoomSharedFile": {
      "range": "210,606",
      "errors": {
        "group_authorization": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getChatRoomAttributes": {
      "range": "110,606",
      "errors": {
        "illegal_argument": {
          "code": 110,
          "httpStatus": 400,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "setChatRoomAttributes": {
      "range": "110,210,702,703,4",
      "errors": {
        "illegal_argument": {
          "code": 110,
          "httpStatus": 400,
          "retryable": false
        },
        "chatroom_not_joined": {
          "code": 702,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60011
        },
        "chatroom_permission_denied": {
          "code": 703,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60010
        },
        "exceed_limit": {
          "code": 4,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60012
        },
        "MetadataException": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        }
      }
    },
    "setChatRoomAttribute": {
      "range": "110,210,702,703,4",
      "errors": {
        "illegal_argument": {
          "code": 110,
          "httpStatus": 400,
          "retryable": false
        },
        "chatroom_not_joined": {
          "code": 702,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60011
        },
        "chatroom_permission_denied": {
          "code": 703,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60010
        },
        "exceed_limit": {
          "code": 4,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60012
        },
        "MetadataException": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        }
      }
    },
    "removeChatRoomAttributes": {
      "range": "110,210,702,703,4",
      "errors": {
        "illegal_argument": {
          "code": 110,
          "httpStatus": 400,
          "retryable": false
        },
        "chatroom_not_joined": {
          "code": 702,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60011
        },
        "chatroom_permission_denied": {
          "code": 703,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60010
        },
        "exceed_limit": {
          "code": 4,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60012
        },
        "MetadataException": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        }
      }
    },
    "removeChatRoomAttribute": {
      "range": "110,210,702,703,4",
      "errors": {
        "illegal_argument": {
          "code": 110,
          "httpStatus": 400,
          "retryable": false
        },
        "chatroom_not_joined": {
          "code": 702,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60011
        },
        "chatroom_permission_denied": {
          "code": 703,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60010
        },
        "exceed_limit": {
          "code": 4,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60012
        },
        "MetadataException": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false
        }
      }
    }
  }
} as const;
