// Auto-generated by scripts/generate-runtime-error-maps.mjs. Do not edit manually.

export const COMMON_ERROR_MAP = {
  "common": {
    "validation": {
      "range": "100-110",
      "errors": {
        "MISSING_REQUIRED": {
          "code": 110
        },
        "INVALID_FORMAT": {
          "code": 110
        },
        "UNKNOWN": {
          "code": 110
        }
      }
    },
    "auth": {
      "range": "108,200-215",
      "errors": {
        "ALREADY_LOGIN": {
          "code": 200
        },
        "NOT_LOGIN": {
          "code": 201
        },
        "UNAUTHORIZED": {
          "code": 202
        },
        "FORBIDDEN": {
          "code": 210
        },
        "TOKEN_EXPIRED": {
          "code": 108
        },
        "BIND_ANOTHER_DEVICE": {
          "code": 213
        },
        "LOGIN_TOO_MANY_DEVICES": {
          "code": 214
        },
        "USER_MUTED": {
          "code": 215
        }
      }
    },
    "connection": {
      "range": "1,100,202,300-304",
      "errors": {
        "TIMEOUT": {
          "code": 301
        },
        "WEBSOCKET_ERROR": {
          "code": 300
        },
        "NOT_CREATED": {
          "code": 1
        },
        "CLOSED_BEFORE_READY": {
          "code": 300
        },
        "CANCELLED": {
          "code": 1
        },
        "PROVISION_TIMEOUT": {
          "code": 301
        },
        "PROVISION_REJECTED": {
          "code": 202
        },
        "PROVISION_CLOSED": {
          "code": 300
        },
        "DNSLIST_FAILED": {
          "code": 304
        },
        "SERVER_BUSY": {
          "code": 302
        }
      }
    },
    "storage": {
      "range": "3",
      "errors": {
        "OPERATION_FAILED": {
          "code": 3
        }
      }
    },
    "message": {
      "range": "1,300-511",
      "errors": {
        "NOT_CONNECTED": {
          "code": 300
        },
        "ACK_TIMEOUT": {
          "code": 301
        },
        "SEND_FAILED": {
          "code": 303
        },
        "SENDER_DESTROYED": {
          "code": 1
        },
        "ENCODE_FAILED": {
          "code": 500
        },
        "DECODE_FAILED": {
          "code": 500
        },
        "ACK_MISSING": {
          "code": 301
        }
      }
    },
    "transport": {
      "range": "2,301,303",
      "errors": {
        "NETWORK_ERROR": {
          "code": 2
        },
        "TIMEOUT": {
          "code": 301
        },
        "HTTP_ERROR": {
          "code": 303
        },
        "BUSINESS_UNKNOWN": {
          "code": 303
        }
      }
    },
    "upload": {
      "range": "1,100,110,301,402,405",
      "errors": {
        "REQUIRED_FIELD_MISSING": {
          "code": 110
        },
        "INVALID_APPKEY": {
          "code": 100
        },
        "SIZE_EXCEEDED": {
          "code": 405
        },
        "REQUEST_FAILED": {
          "code": 402
        },
        "TIMEOUT": {
          "code": 301
        },
        "ABORTED": {
          "code": 1
        }
      }
    },
    "unknown": {
      "range": "1,4",
      "errors": {
        "UNKNOWN": {
          "code": 1
        },
        "SERVICE_LIMIT_EXCEEDED": {
          "code": 4
        }
      }
    },
    "push": {
      "range": "1500,1501,1502",
      "errors": {
        "TOKEN_UPLOAD_FAILED": {
          "code": 1500
        },
        "SILENT_MODE_OPERATION_FAILED": {
          "code": 1501
        },
        "PUSH_LANGUAGE_OPERATION_FAILED": {
          "code": 1502
        }
      }
    },
    "chatroom": {
      "range": "700-707",
      "errors": {
        "CHATROOM_INVALID_ID": {
          "code": 700
        },
        "CHATROOM_NOT_JOINED": {
          "code": 702
        },
        "CHATROOM_PERMISSION_DENIED": {
          "code": 703
        },
        "CHATROOM_MEMBERS_FULL": {
          "code": 704
        },
        "CHATROOM_NOT_EXIST": {
          "code": 705
        },
        "CHATROOM_OWNER_NOT_ALLOW_LEAVE": {
          "code": 706
        },
        "CHATROOM_USER_IN_BLOCKLIST": {
          "code": 707
        }
      }
    }
  },
  "apis": {}
} as const;
