// Auto-generated by scripts/generate-runtime-error-maps.mjs. Do not edit manually.

export const CONTACT_ERROR_MAP = {
  "common": {},
  "apis": {
    "addContact": {
      "range": "110,204,210,1000,1001,1002",
      "localErrors": {
        "addContact": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "USER_NOT_FOUND": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false
        },
        "ALREADY_FRIEND": {
          "code": 1000,
          "retryable": false
        },
        "BLOCKED_BY_USER": {
          "code": 210,
          "retryable": false
        },
        "CONTACT_REACH_LIMIT": {
          "code": 1001,
          "httpStatus": 403,
          "retryable": false,
          "matchField": "error_description",
          "matchPattern": "Inviter's contact max count"
        },
        "CONTACT_REACH_LIMIT_PEER": {
          "code": 1002,
          "httpStatus": 403,
          "retryable": false,
          "matchField": "error_description",
          "matchPattern": "Invitee's contact max count"
        }
      }
    },
    "deleteContact": {
      "range": "110,204",
      "localErrors": {
        "deleteContact": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "USER_NOT_FOUND": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "acceptContactInvite": {
      "range": "110,204,1001,1002",
      "localErrors": {
        "acceptContactInvite": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "USER_NOT_FOUND": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false
        },
        "CONTACT_REACH_LIMIT": {
          "code": 1001,
          "httpStatus": 403,
          "retryable": false,
          "matchField": "error_description",
          "matchPattern": "Inviter's contact max count"
        },
        "CONTACT_REACH_LIMIT_PEER": {
          "code": 1002,
          "httpStatus": 403,
          "retryable": false,
          "matchField": "error_description",
          "matchPattern": "Invitee's contact max count"
        }
      }
    },
    "declineContactInvite": {
      "range": "110,204",
      "localErrors": {
        "declineContactInvite": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "USER_NOT_FOUND": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "setContactRemark": {
      "range": "4,110,223",
      "localErrors": {
        "setContactRemark": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "illegal_argument": {
          "code": 223,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_description",
          "matchPattern": "please add as a friend first"
        },
        "remark_length_exceeded": {
          "code": 4,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_description",
          "matchPattern": "remark length must less than"
        }
      }
    },
    "getBlocklist": {
      "range": "",
      "errors": {}
    },
    "addUsersToBlocklist": {
      "range": "4,110,204",
      "localErrors": {
        "addUsersToBlocklist": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "service_resource_not_found": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false
        },
        "blocklist_limit_exceeded": {
          "code": 4,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_description",
          "matchPattern": "almost reached or been greater than the upper range"
        }
      }
    },
    "removeUserFromBlocklist": {
      "range": "110",
      "localErrors": {
        "removeUserFromBlocklist": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {}
    }
  }
} as const;
