// Auto-generated by scripts/generate-runtime-error-maps.mjs. Do not edit manually.

export const CORE_ERROR_MAP = {
  "common": {},
  "apis": {
    "getSelfIdsOnOtherPlatform": {
      "range": "202,300-303",
      "errors": {}
    }
  }
} as const;
