// Auto-generated by scripts/generate-runtime-error-maps.mjs. Do not edit manually.

export const GROUP_ERROR_MAP = {
  "common": {},
  "apis": {
    "createGroup": {
      "range": "4,110,204,608",
      "errors": {
        "invalid_parameter": {
          "code": 110,
          "httpStatus": 400,
          "retryable": false
        },
        "illegal_argument": {
          "code": 110,
          "httpStatus": 400,
          "retryable": false
        },
        "exceed_limit": {
          "code": 4,
          "httpStatus": 403,
          "retryable": false
        },
        "group_name_violation": {
          "code": 608,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "INVALID_GROUP_NAME"
          ]
        },
        "resource_not_found": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found",
            "username_not_found"
          ]
        }
      }
    },
    "getGroupInfo": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getGroupInfoList": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "updateGroupInfo": {
      "range": "110,603,606,607,608",
      "errors": {
        "group_authorization": {
          "code": 603,
          "httpStatus": 403,
          "retryable": false
        },
        "forbidden_op": {
          "code": 603,
          "httpStatus": 403,
          "retryable": false
        },
        "illegal_argument": {
          "code": 110,
          "httpStatus": 400,
          "retryable": false
        },
        "exceed_limit": {
          "code": 110,
          "httpStatus": 403,
          "retryable": false
        },
        "group_name_violation": {
          "code": 608,
          "httpStatus": 403,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        },
        "group_disabled": {
          "code": 607,
          "httpStatus": 403,
          "retryable": false
        }
      }
    },
    "changeGroupOwner": {
      "range": "603,606",
      "errors": {
        "forbidden_op": {
          "code": 603,
          "httpStatus": 403,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "destroyGroup": {
      "range": "603,606,607",
      "errors": {
        "group_authorization": {
          "code": 603,
          "httpStatus": 403,
          "retryable": false
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        },
        "group_disabled": {
          "code": 607,
          "httpStatus": 403,
          "retryable": false
        }
      }
    },
    "leaveGroup": {
      "range": "602,603,606",
      "errors": {
        "not_joined": {
          "code": 602,
          "retryable": false,
          "aliases": [
            "GROUP_NOT_JOINED",
            "group_not_joined"
          ]
        },
        "owner_cannot_leave": {
          "code": 603,
          "httpStatus": 403,
          "retryable": false,
          "matchField": "error_description",
          "matchPattern": "owner can not quit group"
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "joinGroup": {
      "range": "600-607,613",
      "errors": {
        "group_invalid_id": {
          "code": 600,
          "retryable": false,
          "aliases": [
            "GROUP_INVALID_ID"
          ]
        },
        "already_joined": {
          "code": 601,
          "retryable": false,
          "aliases": [
            "ALREADY_JOINED",
            "GROUP_ALREADY_JOINED",
            "group_already_joined"
          ]
        },
        "not_joined": {
          "code": 602,
          "retryable": false,
          "aliases": [
            "GROUP_NOT_JOINED",
            "group_not_joined"
          ]
        },
        "group_authorization": {
          "code": 603,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "NEED_APPROVAL",
            "GROUP_PERMISSION_DENIED"
          ]
        },
        "group_full": {
          "code": 604,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "GROUP_FULL",
            "GROUP_MEMBERS_FULL"
          ],
          "matchField": "error_description",
          "matchPattern": "member list is full"
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "GROUP_NOT_FOUND",
            "service_resource_not_found"
          ]
        },
        "group_disabled": {
          "code": 607,
          "retryable": false,
          "aliases": [
            "GROUP_DISABLED"
          ]
        },
        "group_user_in_blocklist": {
          "code": 613,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "GROUP_USER_IN_BLOCKLIST"
          ],
          "matchField": "error_description",
          "matchPattern": "is in the blacklist"
        }
      }
    },
    "inviteUsersToGroup": {
      "range": "204,603,606,607",
      "errors": {
        "group_authorization": {
          "code": 603,
          "httpStatus": 400,
          "retryable": false
        },
        "resource_not_found": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found",
            "username_not_found"
          ]
        },
        "group_not_found": {
          "code": 606,
          "retryable": false,
          "aliases": [
            "GROUP_NOT_FOUND"
          ]
        },
        "group_disabled": {
          "code": 607,
          "retryable": false
        }
      }
    },
    "getGroupMemberList": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found"
          ]
        }
      }
    },
    "getGroupAdminList": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getGroupMuteList": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getGroupBlocklist": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getGroupAllowlist": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getGroupAnnouncement": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false
        }
      }
    },
    "getGroupSharedFileList": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "RestGroupFeignException"
          ]
        }
      }
    },
    "deleteGroupSharedFile": {
      "range": "603,605,606",
      "errors": {
        "group_authorization": {
          "code": 603,
          "retryable": false
        },
        "file_not_found": {
          "code": 605,
          "retryable": false,
          "aliases": [
            "GROUP_SHARED_FILE_INVALID_ID"
          ]
        },
        "resource_not_found": {
          "code": 606,
          "retryable": false
        }
      }
    },
    "setGroupMemberAttributes": {
      "range": "4,210,302,305,602,609-612",
      "errors": {
        "attributes_reach_limit": {
          "code": 609,
          "retryable": false,
          "aliases": [
            "GROUP_MEMBER_ATTRIBUTES_REACH_LIMIT"
          ],
          "matchField": "error_code",
          "matchValue": 60006
        },
        "attributes_update_failed": {
          "code": 610,
          "retryable": false,
          "aliases": [
            "GROUP_MEMBER_ATTRIBUTES_UPDATE_FAILED"
          ],
          "matchField": "error_code",
          "matchValue": 60005
        },
        "attributes_key_reach_limit": {
          "code": 611,
          "retryable": false,
          "aliases": [
            "GROUP_MEMBER_ATTRIBUTES_KEY_REACH_LIMIT"
          ],
          "matchField": "error_code",
          "matchValue": 60009
        },
        "attributes_value_reach_limit": {
          "code": 612,
          "retryable": false,
          "aliases": [
            "GROUP_MEMBER_ATTRIBUTES_VALUE_REACH_LIMIT"
          ],
          "matchField": "error_code",
          "matchValue": 600010
        },
        "not_joined": {
          "code": 602,
          "httpStatus": 404,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60003
        },
        "permission_denied": {
          "code": 210,
          "httpStatus": 401,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60001
        },
        "permission_denied_403": {
          "code": 210,
          "httpStatus": 403,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60002
        },
        "exceed_service_limit": {
          "code": 4,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60007
        },
        "service_disabled": {
          "code": 305,
          "httpStatus": 403,
          "retryable": false,
          "matchField": "error_code",
          "matchValue": 60004
        }
      }
    },
    "getGroupMembersAttributes": {
      "range": "606",
      "errors": {
        "resource_not_found": {
          "code": 606,
          "retryable": false
        }
      }
    }
  }
} as const;
