// Auto-generated by scripts/generate-runtime-error-maps.mjs. Do not edit manually.

export const PRESENCE_ERROR_MAP = {
  "common": {},
  "apis": {
    "publishPresence": {
      "range": "1100",
      "errors": {
        "PRESENCE_PARAM_EXCEED": {
          "code": 1100,
          "httpStatus": 400,
          "retryable": false
        }
      }
    },
    "subscribePresences": {
      "range": "1100,1101",
      "errors": {
        "cannot_subscribe_yourself": {
          "code": 1101,
          "httpStatus": 400,
          "retryable": false,
          "matchField": "result",
          "matchPattern": "you can't sub yourself"
        },
        "param_length_exceed": {
          "code": 1100,
          "httpStatus": 400,
          "retryable": false
        }
      }
    },
    "unsubscribePresence": {
      "range": "1100",
      "errors": {
        "param_length_exceed": {
          "code": 1100,
          "httpStatus": 400,
          "retryable": false
        }
      }
    },
    "getSubscribedPresenceList": {
      "range": "1100",
      "errors": {
        "param_length_exceed": {
          "code": 1100,
          "httpStatus": 400,
          "retryable": false
        }
      }
    },
    "getPresenceStatus": {
      "range": "1100",
      "errors": {
        "param_length_exceed": {
          "code": 1100,
          "httpStatus": 400,
          "retryable": false
        }
      }
    }
  }
} as const;
