// Auto-generated by scripts/generate-runtime-error-maps.mjs. Do not edit manually.

export const PUSH_ERROR_MAP = {
  "common": {},
  "apis": {
    "setGlobalSilentMode": {
      "range": "110,1501",
      "localErrors": {
        "setGlobalSilentMode": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "SILENT_MODE_OPERATION_FAILED": {
          "code": 1501,
          "httpStatus": 400,
          "retryable": false
        }
      }
    },
    "setConversationSilentMode": {
      "range": "110,1501",
      "localErrors": {
        "setConversationSilentMode": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "SILENT_MODE_OPERATION_FAILED": {
          "code": 1501,
          "httpStatus": 400,
          "retryable": false
        }
      }
    },
    "setPushLanguage": {
      "range": "110,1502",
      "localErrors": {
        "setPushLanguage": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "PUSH_LANGUAGE_OPERATION_FAILED": {
          "code": 1502,
          "httpStatus": 400,
          "retryable": false
        }
      }
    },
    "uploadPushToken": {
      "range": "110,1500",
      "localErrors": {
        "uploadPushToken": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "TOKEN_UPLOAD_FAILED": {
          "code": 1500,
          "httpStatus": 400,
          "retryable": true
        }
      }
    },
    "getGlobalSilentMode": {
      "range": "1501",
      "errors": {
        "SILENT_MODE_OPERATION_FAILED": {
          "code": 1501
        }
      }
    },
    "getConversationSilentMode": {
      "range": "110,1501",
      "localErrors": {
        "getConversationSilentMode": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "SILENT_MODE_OPERATION_FAILED": {
          "code": 1501
        }
      }
    },
    "clearConversationRemindType": {
      "range": "110,1501",
      "localErrors": {
        "clearConversationRemindType": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "SILENT_MODE_OPERATION_FAILED": {
          "code": 1501
        }
      }
    },
    "getConversationSilentModes": {
      "range": "110,1501",
      "localErrors": {
        "getConversationSilentModes": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "SILENT_MODE_OPERATION_FAILED": {
          "code": 1501
        }
      }
    },
    "getConversationListByRemindType": {
      "range": "110",
      "localErrors": {
        "getConversationListByRemindType": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {}
    },
    "getPushLanguage": {
      "range": "1502",
      "errors": {
        "PUSH_LANGUAGE_OPERATION_FAILED": {
          "code": 1502
        }
      }
    }
  }
} as const;
