// Auto-generated by scripts/generate-runtime-error-maps.mjs. Do not edit manually.

export const THREAD_ERROR_MAP = {
  "common": {},
  "apis": {
    "createChatThread": {
      "range": "4,110,201,210,301,303,606",
      "localErrors": {
        "createChatThread": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "not_login": {
          "code": 201,
          "httpStatus": 401,
          "retryable": false,
          "aliases": [
            "unauthorized"
          ]
        },
        "permission_denied": {
          "code": 210,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "group_authorization",
            "forbidden"
          ]
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found",
            "GROUP_NOT_FOUND"
          ]
        },
        "service_limit_exceeded": {
          "code": 4,
          "httpStatus": 400,
          "retryable": false,
          "aliases": [
            "limit_exceeded"
          ]
        },
        "request_timeout": {
          "code": 301,
          "httpStatus": 504,
          "retryable": true,
          "aliases": [
            "timeout"
          ]
        },
        "service_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true,
          "aliases": [
            "server_unknown_error"
          ]
        }
      }
    },
    "getChatThreadList": {
      "range": "110,201,210,301,303,606",
      "localErrors": {
        "getChatThreadList": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "not_login": {
          "code": 201,
          "httpStatus": 401,
          "retryable": false,
          "aliases": [
            "unauthorized"
          ]
        },
        "permission_denied": {
          "code": 210,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "group_authorization",
            "forbidden"
          ]
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found",
            "GROUP_NOT_FOUND"
          ]
        },
        "request_timeout": {
          "code": 301,
          "httpStatus": 504,
          "retryable": true,
          "aliases": [
            "timeout"
          ]
        },
        "service_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true,
          "aliases": [
            "server_unknown_error"
          ]
        }
      }
    },
    "getJoinedChatThreadList": {
      "range": "110,201,210,301,303,606",
      "localErrors": {
        "getJoinedChatThreadList": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "not_login": {
          "code": 201,
          "httpStatus": 401,
          "retryable": false,
          "aliases": [
            "unauthorized"
          ]
        },
        "permission_denied": {
          "code": 210,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "group_authorization",
            "forbidden"
          ]
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found",
            "GROUP_NOT_FOUND"
          ]
        },
        "request_timeout": {
          "code": 301,
          "httpStatus": 504,
          "retryable": true,
          "aliases": [
            "timeout"
          ]
        },
        "service_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true,
          "aliases": [
            "server_unknown_error"
          ]
        }
      }
    },
    "getChatThreadInfo": {
      "range": "110,201,210,301,303,606",
      "localErrors": {
        "getChatThreadInfo": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        },
        "getInfo": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        },
        "refresh": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "not_login": {
          "code": 201,
          "httpStatus": 401,
          "retryable": false,
          "aliases": [
            "unauthorized"
          ]
        },
        "permission_denied": {
          "code": 210,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "group_authorization",
            "forbidden"
          ]
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found",
            "THREAD_NOT_FOUND"
          ]
        },
        "request_timeout": {
          "code": 301,
          "httpStatus": 504,
          "retryable": true,
          "aliases": [
            "timeout"
          ]
        },
        "service_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true,
          "aliases": [
            "server_unknown_error"
          ]
        }
      }
    },
    "joinChatThread": {
      "range": "4,110,201,210,301,303,606",
      "localErrors": {
        "joinChatThread": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        },
        "join": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "not_login": {
          "code": 201,
          "httpStatus": 401,
          "retryable": false,
          "aliases": [
            "unauthorized"
          ]
        },
        "permission_denied": {
          "code": 210,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "group_authorization",
            "forbidden"
          ]
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found",
            "THREAD_NOT_FOUND"
          ]
        },
        "service_limit_exceeded": {
          "code": 4,
          "httpStatus": 400,
          "retryable": false,
          "aliases": [
            "limit_exceeded"
          ]
        },
        "request_timeout": {
          "code": 301,
          "httpStatus": 504,
          "retryable": true,
          "aliases": [
            "timeout"
          ]
        },
        "service_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true,
          "aliases": [
            "server_unknown_error"
          ]
        }
      }
    },
    "leaveChatThread": {
      "range": "110,201,210,301,303,606",
      "localErrors": {
        "leaveChatThread": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        },
        "leave": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "not_login": {
          "code": 201,
          "httpStatus": 401,
          "retryable": false,
          "aliases": [
            "unauthorized"
          ]
        },
        "permission_denied": {
          "code": 210,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "group_authorization",
            "forbidden"
          ]
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found",
            "THREAD_NOT_FOUND"
          ]
        },
        "request_timeout": {
          "code": 301,
          "httpStatus": 504,
          "retryable": true,
          "aliases": [
            "timeout"
          ]
        },
        "service_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true,
          "aliases": [
            "server_unknown_error"
          ]
        }
      }
    },
    "destroyChatThread": {
      "range": "110,201,210,301,303,606",
      "localErrors": {
        "destroyChatThread": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        },
        "destroy": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "not_login": {
          "code": 201,
          "httpStatus": 401,
          "retryable": false,
          "aliases": [
            "unauthorized"
          ]
        },
        "permission_denied": {
          "code": 210,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "group_authorization",
            "forbidden"
          ]
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found",
            "THREAD_NOT_FOUND"
          ]
        },
        "request_timeout": {
          "code": 301,
          "httpStatus": 504,
          "retryable": true,
          "aliases": [
            "timeout"
          ]
        },
        "service_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true,
          "aliases": [
            "server_unknown_error"
          ]
        }
      }
    },
    "updateChatThreadName": {
      "range": "110,201,210,301,303,606",
      "localErrors": {
        "updateChatThreadName": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        },
        "updateName": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "not_login": {
          "code": 201,
          "httpStatus": 401,
          "retryable": false,
          "aliases": [
            "unauthorized"
          ]
        },
        "permission_denied": {
          "code": 210,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "group_authorization",
            "forbidden"
          ]
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found",
            "THREAD_NOT_FOUND"
          ]
        },
        "request_timeout": {
          "code": 301,
          "httpStatus": 504,
          "retryable": true,
          "aliases": [
            "timeout"
          ]
        },
        "service_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true,
          "aliases": [
            "server_unknown_error"
          ]
        }
      }
    },
    "getChatThreadMemberList": {
      "range": "110,201,210,301,303,606",
      "localErrors": {
        "getChatThreadMemberList": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        },
        "getMemberList": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "not_login": {
          "code": 201,
          "httpStatus": 401,
          "retryable": false,
          "aliases": [
            "unauthorized"
          ]
        },
        "permission_denied": {
          "code": 210,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "group_authorization",
            "forbidden"
          ]
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found",
            "THREAD_NOT_FOUND"
          ]
        },
        "request_timeout": {
          "code": 301,
          "httpStatus": 504,
          "retryable": true,
          "aliases": [
            "timeout"
          ]
        },
        "service_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true,
          "aliases": [
            "server_unknown_error"
          ]
        }
      }
    },
    "removeChatThreadMember": {
      "range": "110,201,210,301,303,606",
      "localErrors": {
        "removeChatThreadMember": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        },
        "removeMember": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "not_login": {
          "code": 201,
          "httpStatus": 401,
          "retryable": false,
          "aliases": [
            "unauthorized"
          ]
        },
        "permission_denied": {
          "code": 210,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "group_authorization",
            "forbidden"
          ]
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found",
            "THREAD_NOT_FOUND"
          ]
        },
        "request_timeout": {
          "code": 301,
          "httpStatus": 504,
          "retryable": true,
          "aliases": [
            "timeout"
          ]
        },
        "service_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true,
          "aliases": [
            "server_unknown_error"
          ]
        }
      }
    },
    "getChatThreadLastMessageList": {
      "range": "110,201,210,301,303,606",
      "localErrors": {
        "getChatThreadLastMessageList": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "not_login": {
          "code": 201,
          "httpStatus": 401,
          "retryable": false,
          "aliases": [
            "unauthorized"
          ]
        },
        "permission_denied": {
          "code": 210,
          "httpStatus": 403,
          "retryable": false,
          "aliases": [
            "group_authorization",
            "forbidden"
          ]
        },
        "resource_not_found": {
          "code": 606,
          "httpStatus": 404,
          "retryable": false,
          "aliases": [
            "service_resource_not_found",
            "THREAD_NOT_FOUND"
          ]
        },
        "request_timeout": {
          "code": 301,
          "httpStatus": 504,
          "retryable": true,
          "aliases": [
            "timeout"
          ]
        },
        "service_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true,
          "aliases": [
            "server_unknown_error"
          ]
        }
      }
    }
  }
} as const;
