// Auto-generated by scripts/generate-runtime-error-maps.mjs. Do not edit manually.

export const USER_INFO_ERROR_MAP = {
  "common": {},
  "apis": {
    "updateOwnUserInfo": {
      "range": "4,110,204,901",
      "localErrors": {
        "updateOwnInfo": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        },
        "updateOwnInfoByAttribute": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "data_length_exceed": {
          "code": 901,
          "httpStatus": 403,
          "retryable": false
        },
        "resource_not_found": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false
        },
        "rate_limit": {
          "code": 4,
          "httpStatus": 429,
          "retryable": true
        }
      }
    },
    "getUserInfoByUserId": {
      "range": "4,110,204,900",
      "localErrors": {
        "getUserInfoByUserId": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "usercount_exceed": {
          "code": 900,
          "httpStatus": 400,
          "retryable": false
        },
        "resource_not_found": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false
        },
        "rate_limit": {
          "code": 4,
          "httpStatus": 429,
          "retryable": true
        }
      }
    },
    "getUserInfoByAttribute": {
      "range": "4,110,204,900",
      "localErrors": {
        "getUserInfoByAttribute": {
          "validation_invalid": {
            "code": 110,
            "retryable": false
          }
        }
      },
      "errors": {
        "usercount_exceed": {
          "code": 900,
          "httpStatus": 400,
          "retryable": false
        },
        "resource_not_found": {
          "code": 204,
          "httpStatus": 404,
          "retryable": false
        },
        "rate_limit": {
          "code": 4,
          "httpStatus": 429,
          "retryable": true
        }
      }
    },
    "subscribeUsersInfo": {
      "range": "4,202,210,303,1600,1601",
      "errors": {
        "unauthorized": {
          "code": 202,
          "httpStatus": 401
        },
        "forbidden": {
          "code": 210,
          "httpStatus": 403,
          "aliases": [
            "operation forbidden"
          ],
          "matchField": "error_description",
          "matchPattern": "metadata subscription not allow"
        },
        "subscriber_limit_exceeded": {
          "code": 1600,
          "httpStatus": 400,
          "matchField": "error_description",
          "matchPattern": "metadata subscription count exceeds limit"
        },
        "target_limit_exceeded": {
          "code": 1601,
          "httpStatus": 400,
          "matchField": "error_description",
          "matchPattern": "metadata subscribed count exceeds limit"
        },
        "rate_limit": {
          "code": 4,
          "httpStatus": 429,
          "retryable": true
        },
        "server_unknown_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true
        }
      }
    },
    "unsubscribeUsersInfo": {
      "range": "4,202,210,303,1600,1601",
      "errors": {
        "unauthorized": {
          "code": 202,
          "httpStatus": 401
        },
        "forbidden": {
          "code": 210,
          "httpStatus": 403,
          "aliases": [
            "operation forbidden"
          ],
          "matchField": "error_description",
          "matchPattern": "metadata subscription not allow"
        },
        "subscriber_limit_exceeded": {
          "code": 1600,
          "httpStatus": 400,
          "matchField": "error_description",
          "matchPattern": "metadata subscription count exceeds limit"
        },
        "target_limit_exceeded": {
          "code": 1601,
          "httpStatus": 400,
          "matchField": "error_description",
          "matchPattern": "metadata subscribed count exceeds limit"
        },
        "rate_limit": {
          "code": 4,
          "httpStatus": 429,
          "retryable": true
        },
        "server_unknown_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true
        }
      }
    },
    "getSubscribedUsers": {
      "range": "4,202,210,303,1600,1601",
      "errors": {
        "unauthorized": {
          "code": 202,
          "httpStatus": 401
        },
        "forbidden": {
          "code": 210,
          "httpStatus": 403,
          "aliases": [
            "operation forbidden"
          ],
          "matchField": "error_description",
          "matchPattern": "metadata subscription not allow"
        },
        "subscriber_limit_exceeded": {
          "code": 1600,
          "httpStatus": 400,
          "matchField": "error_description",
          "matchPattern": "metadata subscription count exceeds limit"
        },
        "target_limit_exceeded": {
          "code": 1601,
          "httpStatus": 400,
          "matchField": "error_description",
          "matchPattern": "metadata subscribed count exceeds limit"
        },
        "rate_limit": {
          "code": 4,
          "httpStatus": 429,
          "retryable": true
        },
        "server_unknown_error": {
          "code": 303,
          "httpStatus": 500,
          "retryable": true
        }
      }
    }
  }
} as const;
