/**
 * [zh-CN] 创建消息方法的入参类型定义。
 * [en-US] Parameter type definitions for message creation APIs.
 */

import type {
  ChatConversationType,
  CompatibleFile,
  Message,
  MessagePriority,
} from './index';

/**
 * [zh-CN] 创建消息的通用入参。
 * [en-US] Common parameters for creating messages.
 */
export interface CreateMessageBaseParams {
  /** [zh-CN] 会话 ID；单聊为对端用户 ID，群聊为 groupId，聊天室为 chatroomId。 [en-US] Conversation ID; peer user ID for one-to-one chat, groupId for group chat, and chatroomId for chat room. */
  conversationId: string;
  /** [zh-CN] 会话类型。 [en-US] Conversation type. */
  conversationType: ChatConversationType;
  /** [zh-CN] 消息扩展字段，需保持 JSON 可序列化。 [en-US] Message extension payload, which should be JSON-serializable. */
  ext?: Record<string, unknown>;
  /** [zh-CN] 本地时间戳，单位毫秒；不传时由 SDK 生成。 [en-US] Local timestamp in milliseconds; generated by the SDK when omitted. */
  timestamp?: number;
  /** [zh-CN] 定向消息接收者列表。 [en-US] Target receiver list for directed messages. */
  receiverList?: string[];
  /** [zh-CN] 是否仅投递给在线用户。 [en-US] Whether to deliver only to online users. */
  deliverOnlineOnly?: boolean;
  /** [zh-CN] 发送消息协议中的 webhookEnv 字段。 [en-US] The webhookEnv field in the sending message protocol. */
  webhookEnv?: string;
  /** [zh-CN] 消息优先级。 [en-US] Message priority. */
  priority?: MessagePriority;
  /** [zh-CN] 是否需要群已读回执，仅群聊有效。 [en-US] Whether group read receipt is requested; only valid for group chat. */
  needGroupReadReceipt?: boolean;
}

/**
 * [zh-CN] 创建文本消息的入参。
 * [en-US] Parameters for creating a text message.
 */
export interface CreateTextMessageParams extends CreateMessageBaseParams {
  /** [zh-CN] 文本消息内容。 [en-US] Text message content. */
  content: string;
  /** [zh-CN] 发送时需要翻译到的目标语言列表。 [en-US] Target languages to translate to when sending. */
  targetLanguages?: string[];
}

/**
 * [zh-CN] 创建图片消息的入参。`data` 与 `originalUrl` 至少传一个；传 `data` 时 SDK 会自动补齐文件信息，并在发送前解析图片宽高。
 * [en-US] Parameters for creating an image message. Either `data` or `originalUrl` is required. When `data` is provided, the SDK fills file metadata and resolves image dimensions before sending.
 */
export interface CreateImageMessageParams extends CreateMessageBaseParams {
  /** [zh-CN] 本地文件对象。 [en-US] Local file object. */
  data?: CompatibleFile;
  /** [zh-CN] 远程原图地址。 [en-US] Remote original image URL. */
  originalUrl?: string;
  /** [zh-CN] 文件名；传 `data` 时可由 SDK 自动获取。 [en-US] Filename; auto-resolved from `data` when available. */
  filename?: string;
  /** [zh-CN] 文件 MIME 类型；传 `data` 时可由 SDK 自动获取。 [en-US] File MIME type; auto-resolved from `data` when available. */
  filetype?: string;
  /** [zh-CN] 图片宽度，单位像素。 [en-US] Image width in pixels. */
  width?: number;
  /** [zh-CN] 图片高度，单位像素。 [en-US] Image height in pixels. */
  height?: number;
  /** [zh-CN] 是否为 GIF。 [en-US] Whether the image is a GIF. */
  isGif?: boolean;
  /** [zh-CN] 是否按原图语义发送。 [en-US] Whether to send with original-image semantics. */
  isOriginalImage?: boolean;
  /** [zh-CN] 文件大小，单位字节。 [en-US] File size in bytes. */
  fileLength?: number;
  /** [zh-CN] 缩略图地址。 [en-US] Thumbnail URL. */
  thumbnailUrl?: string;
}

/**
 * [zh-CN] 创建文件消息的入参。`data` 与 `originalUrl` 至少传一个。
 * [en-US] Parameters for creating a file message. Either `data` or `originalUrl` is required.
 */
export interface CreateFileMessageParams extends CreateMessageBaseParams {
  /** [zh-CN] 本地文件对象。 [en-US] Local file object. */
  data?: CompatibleFile;
  /** [zh-CN] 远程文件地址。 [en-US] Remote file URL. */
  originalUrl?: string;
  /** [zh-CN] 文件名；传 `data` 时可由 SDK 自动获取。 [en-US] Filename; auto-resolved from `data` when available. */
  filename?: string;
  /** [zh-CN] 文件 MIME 类型；传 `data` 时可由 SDK 自动获取。 [en-US] File MIME type; auto-resolved from `data` when available. */
  filetype?: string;
  /** [zh-CN] 文件大小，单位字节。 [en-US] File size in bytes. */
  fileSize?: number;
  /** [zh-CN] 文件长度，单位字节；兼容服务端字段。 [en-US] File length in bytes; compatible with the server field. */
  fileLength?: number;
}

/**
 * [zh-CN] 创建语音消息的入参。`data` 与 `originalUrl` 至少传一个。
 * [en-US] Parameters for creating a voice message. Either `data` or `originalUrl` is required.
 */
export interface CreateVoiceMessageParams extends CreateMessageBaseParams {
  /** [zh-CN] 本地语音文件对象。 [en-US] Local voice file object. */
  data?: CompatibleFile;
  /** [zh-CN] 远程语音地址。 [en-US] Remote voice URL. */
  originalUrl?: string;
  /** [zh-CN] 文件名；传 `data` 时可由 SDK 自动获取。 [en-US] Filename; auto-resolved from `data` when available. */
  filename?: string;
  /** [zh-CN] 文件 MIME 类型；传 `data` 时可由 SDK 自动获取。 [en-US] File MIME type; auto-resolved from `data` when available. */
  filetype?: string;
  /** [zh-CN] 语音时长，单位秒。 [en-US] Voice duration in seconds. */
  duration: number;
  /** [zh-CN] 文件大小，单位字节。 [en-US] File size in bytes. */
  fileLength?: number;
}

/**
 * [zh-CN] 创建视频消息的入参。`data` 与 `originalUrl` 至少传一个。
 * [en-US] Parameters for creating a video message. Either `data` or `originalUrl` is required.
 */
export interface CreateVideoMessageParams extends CreateMessageBaseParams {
  /** [zh-CN] 本地视频文件对象。 [en-US] Local video file object. */
  data?: CompatibleFile;
  /** [zh-CN] 远程视频地址。 [en-US] Remote video URL. */
  originalUrl?: string;
  /** [zh-CN] 文件名；传 `data` 时可由 SDK 自动获取。 [en-US] Filename; auto-resolved from `data` when available. */
  filename?: string;
  /** [zh-CN] 文件 MIME 类型；传 `data` 时可由 SDK 自动获取。 [en-US] File MIME type; auto-resolved from `data` when available. */
  filetype?: string;
  /** [zh-CN] 视频时长，单位秒。 [en-US] Video duration in seconds. */
  duration: number;
  /** [zh-CN] 视频宽度，单位像素。 [en-US] Video width in pixels. */
  width?: number;
  /** [zh-CN] 视频高度，单位像素。 [en-US] Video height in pixels. */
  height?: number;
  /** [zh-CN] 文件大小，单位字节。 [en-US] File size in bytes. */
  fileLength?: number;
  /** [zh-CN] 视频缩略图地址。 [en-US] Video thumbnail URL. */
  thumbnailUrl?: string;
}

/**
 * [zh-CN] 创建位置消息的入参。
 * [en-US] Parameters for creating a location message.
 */
export interface CreateLocationMessageParams extends CreateMessageBaseParams {
  /** [zh-CN] 纬度。 [en-US] Latitude. */
  latitude: number;
  /** [zh-CN] 经度。 [en-US] Longitude. */
  longitude: number;
  /** [zh-CN] 地址描述。 [en-US] Address description. */
  address?: string;
  /** [zh-CN] 建筑名称。 [en-US] Building name. */
  buildingName?: string;
}

/**
 * [zh-CN] 创建命令消息的入参。
 * [en-US] Parameters for creating a command message.
 */
export interface CreateCmdMessageParams extends CreateMessageBaseParams {
  /** [zh-CN] 命令动作。 [en-US] Command action. */
  action: string;
}

/**
 * [zh-CN] 创建自定义消息的入参。
 * [en-US] Parameters for creating a custom message.
 */
export interface CreateCustomMessageParams extends CreateMessageBaseParams {
  /** [zh-CN] 自定义事件名称。 [en-US] Custom event name. */
  event: string;
  /** [zh-CN] 自定义参数。 [en-US] Custom parameters. */
  params?: Record<string, string>;
}

/**
 * [zh-CN] 创建合并消息的入参。
 * [en-US] Parameters for creating a combine message.
 */
export interface CreateCombineMessageParams extends CreateMessageBaseParams {
  /** [zh-CN] 合并消息标题。 [en-US] Combine message title. */
  title: string;
  /** [zh-CN] 合并消息摘要。 [en-US] Combine message summary. */
  summary: string;
  /** [zh-CN] 兼容展示文本，默认 `[聊天记录]`。 [en-US] Fallback display text, defaults to `[聊天记录]`. */
  compatibleText?: string;
  /** [zh-CN] 被合并的消息列表。 [en-US] Messages included in the combine message. */
  messageList: ReadonlyArray<Message>;
}
